### ISSUE TITLE
when training‘train_aanet.py’，TYPE ERROR：_outout_padding（） missed 1 positional argument:‘num_spatial_dims’

### ISSUE THREAD

**Issue by xxxgcat** [guojiajeremy/AANet#2]
![1667530879733](https://user-images.githubusercontent.com/95564137/199876416-d8995212-c436-4945-8549-578feb8fac55.png)

**Comment by guojiajeremy** [comment]
Try lower pytorch version. My version is 1.1.0 or 1.3.1. I believe it is due to the input arguments of the function changed in newer version of pytorch. You can also adapt the arguments according to nn.Transposed3D in your version.

**Comment by xxxgcat** [comment]
> Try lower pytorch version. My version is 1.1.0 or 1.3.1. I believe it is due to the input arguments of the function changed in newer version of pytorch. You can also adapt the arguments according to nn.Transposed3D in your version.

**Thank you very much for your answer, I have implemented the code.**

**Comment by amoreyo** [comment]
> 

are you fix the error by lower pytorch version? if not , can you show the details about the solution?
